eureka.client.serviceUrl.defaultZone=http://${EUREKA_SERVER_ADDRESS:localhost}:8761/eureka

spring.cloud.gateway.discovery.locator.enabled=false

# Custom Routes
spring.cloud.gateway.routes[0].id=currency-exchange
spring.cloud.gateway.routes[0].uri=lb://currency-exchange
spring.cloud.gateway.routes[0].predicates[0]=Path=/currency-exchange/**

spring.cloud.gateway.routes[1].id=currency-conversion
spring.cloud.gateway.routes[1].uri=lb://currency-conversion
spring.cloud.gateway.routes[1].predicates[0]=Path=/currency-conversion/**