eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka

management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

spring.cloud.gateway.discovery.locator.enabled=false

# Custom Routes
spring.cloud.gateway.routes[0].id=currency-exchange
spring.cloud.gateway.routes[0].uri=lb://currency-exchange
spring.cloud.gateway.routes[0].predicates[0]=Path=/currency-exchange/**

spring.cloud.gateway.routes[1].id=currency-conversion
spring.cloud.gateway.routes[1].uri=lb://currency-conversion
spring.cloud.gateway.routes[1].predicates[0]=Path=/currency-conversion/**